name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Ducker hub login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PASS: ${{secrets.DOCKERHUB_TOKEN}}
      run: docker login -u ${{secrets.DOCKERHUB_USER}} -p ${{secrets.DOCKERHUB_TOKEN}}
    - name: Build the Docker image
      run: docker build . --file AnyRest/Dockerfile --tag ${{secrets.DOCKERHUB_USER}}/anyrestdotnet:$(date +%s)
    - name: Docker push
      run: docker push ${{secrets.DOCKERHUB_USER}}/anyrestdotnet
